amazon:
  aws:
    accesskey: ${acess.key}
    secretkey: ${secret.key}
  dynamodb:
    endpoint: http://dynamodb.us-east-1.amazonaws.com

  region: us-east-1

  queue:
    complains: complains
    attendance: attedence
    
server:
  port: 9001
  error:
    include-message: always
    include-binding-errors: always
